// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdzgmhkbzfogkmusuiet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkemdtaGtiemZvZ2ttdXN1aWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDE2OTEsImV4cCI6MjA1ODMxNzY5MX0.AaoBlJN0F2B4kLPWoAODJyUS4VhzZbrhJ4DY7bJytl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});